<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="task.AfterTest" tests="6" skipped="0" failures="0" errors="0" timestamp="2019-09-27T13:35:01" hostname="Zhenyulee-PC" time="0.006">
  <properties/>
  <testcase name="testExceptionThrown()" classname="task.AfterTest" time="0.001"/>
  <testcase name="testGetAfter()" classname="task.AfterTest" time="0.0"/>
  <testcase name="testGetType()" classname="task.AfterTest" time="0.0"/>
  <testcase name="testGetDescription()" classname="task.AfterTest" time="0.0"/>
  <testcase name="testToList()" classname="task.AfterTest" time="0.001"/>
  <testcase name="testGetStatusIcon()" classname="task.AfterTest" time="0.001"/>
  <system-out><![CDATA[I threw exception
]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
